# Generated by Django 4.2.3 on 2023-07-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('permission_level', models.CharField(max_length=20)),
                ('favorite_shoes', models.ManyToManyField(blank=True, related_name='users', to='shoes.shoe')),
            ],
        ),
    ]
