# Generated by Django 4.2.3 on 2023-07-15 07:13

from django.db import migrations, models
import shoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_shoe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image2',
            field=models.ImageField(default='', upload_to=shoes.models.get_shoe_image_path),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image3',
            field=models.ImageField(default='', upload_to=shoes.models.get_shoe_image_path),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image4',
            field=models.ImageField(default='', upload_to=shoes.models.get_shoe_image_path),
        ),
    ]
